### ISSUE TITLE
How to set nref_in and nref_out parameters?

### ISSUE THREAD

**Issue by rsantamariao** [GeoBosh/rbibutils#4]
I have an pubmed xml file with more than 500 references.
I tried to convert to bib file using this code:

bibConvert(infile = fn_med, #fn_med: route to my xml file
outfile = "export.bib",
informat = "med",
outformat = "bib")

But I got only 3 references:
$nref_in
[1] 3

$nref_out
[1] 3

How to set the number of references to read from the input file (nref_in) and number of references to write to the output file (nref_out)?

How to read and write all the references from the source file?

Thanks

**Comment by GeoBosh** [comment]
Thanks for the report.

There is no argument for the number of references - the function should process all references in the file. The number of references on output can be smaller than those read-in if some references in the input caused errors. But in that case you should see some error messages, as well.
 

What you observe is most likely a bug. Alternatively, there could be something wrong in the input file, most likely in the 3rd or 4th reference, but then the function should print some informative message(s).

Can you put here the first 4-5 references from your input file for me to check? It would be even better if you could share the whole file via a link or by email (my email is in file DESCRIPTION).

**Comment by GeoBosh** [comment]
Thanks for the file demonstrating the issue. It was a bug, now fixed on Github. Please let me know if it works and/or if the fix causes new problems.

The function reading the file was implicitly assuming (wrongly) that the end of each reference is on a line by itself and was silently ignoring text on the same line after the end-of-reference tag. Since all the references in the input file were on a single line, everything after the end of the first reference was ignored.

**Comment by rsantamariao** [comment]
Ok.
I checked the update with two different xml files and so far it seems to work perfectly.
Thanks.

**Comment by GeoBosh** [comment]
The fix seems successful. Since this is an essential fix, I uploaded it to CRAN.
